package no.fint.model.administrasjon.kodeverk;

public enum KodeverkActions {
    GET_ALL_ANSVAR,
    GET_ALL_ARBEIDSFORHOLDSTYPE,
    GET_ALL_ART,
    GET_ALL_FUNKSJON,
    GET_ALL_PERSONALRESSURSKATEGORI,
    GET_ALL_PROSJEKT,
    GET_ALL_STILLINGSKODE,
    GET_ALL_TIMERPRUKEKODE,
    GET_ANSVAR,
    GET_ARBEIDSFORHOLDSTYPE,
    GET_ART,
    GET_FUNKSJON,
    GET_PERSONALRESSURSKATEGORI,
    GET_PROSJEKT,
    GET_STILLINGSKODE,
    GET_TIMERPRUKEKODE,
}
